/* NUM01 */

SELECT P.PDNAME AS 제품카테고리, P.PDSUBNAME AS 제품명, F.FACNAME AS 공장명 , S.STONAME AS 판매점명, IFNULL(S.STAMOUNT, 0) AS 판매점재고수량
FROM PRODUCT P
JOIN STORE S ON P.PDNO = S.PDNO
JOIN FACTORY F ON P.FACTNO = F.FACTNO
WHERE F.FACLOC = 'SEOUL' AND (S.STAMOUNT IS NULL OR S.STAMOUNT = 0);

/* NUM02 */

SELECT P.PDSUBNAME AS 제품명, P.PDCOST AS 제품원가, P.PDPRICE AS 제품가격
FROM PRODUCT P
WHERE (P.PDNAME = 'TV' AND P.PDCOST > (SELECT MIN(PDCOST) 
					FROM PRODUCT 
					WHERE PDNAME = 'TV'))
		OR
        (P.PDNAME = 'CELLPHONE' AND P.PDCOST < (SELECT MAX(PDCOST)
					FROM PRODUCT
                    WHERE PDNAME = 'CELLPHONE'));
                    
/* NUM03 */
DROP TABLE DISCARDED_PRODUCT;

CREATE TABLE DISCARDED_PRODUCT
(PDNO INT PRIMARY KEY,
	PDNAME VARCHAR(10),
    PDSUBNAME VARCHAR(10),
    FACTNO VARCHAR(5) REFERENCES FACTORY(FACTNO),
    PDDATE DATE,
    PDCOST INT,
    PDPRICE INT,
    PDAMOUNT INT,
    DISCARDED_DATE DATE);
    
/*NUM04*/


INSERT INTO DISCARDED_PRODUCT (
    PDNO, PDNAME, PDSUBNAME, FACTNO, PDDATE,
    PDCOST, PDPRICE, PDAMOUNT, DISCARDED_DATE
)
SELECT 
    PDNO, PDNAME, PDSUBNAME, P.FACTNO, PDDATE,
    PDCOST, PDPRICE, PDAMOUNT, CURRENT_DATE
FROM PRODUCT P
JOIN FACTORY F ON P.FACTNO = F.FACTNO
WHERE F.FACLOC = 'CHANGWON';

/*NUM05*/

DELETE FROM PRODUCT
WHERE PDNO IN (
	SELECT PDNO FROM DISCARDED_PRODUCT);
    
SELECT * FROM PRODUCT
WHERE PDNO IN (
	SELECT PDNO FROM DISCARDED_PRODUCT);
    
    
