spring.application.name=SpringBootLab01

server.port=9000

# Swagger 설정
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# H2 콘솔 활성화
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
