CREATE TABLE DISCARDED_PRODUCT
(PDNO DECIMAL(8) PRIMARY KEY,
PDNAME VARCHAR(10),
PDSUBNAME VARCHAR(10),
FACTNO VARCHAR(5) REFERENCES FACTORY(FACTNO),
PDDATE DATE,
PDCOST DECIMAL(12),
PDPRICE DECIMAL(12),
PDAMOUNT DECIMAL(12),
DISCARDED_DATE DATE);