CREATE DEFINER=`mydb`@`%` PROCEDURE `test01`()
BEGIN
    SELECT P.PDNAME, P.PDSUBNAME, F.FACNAME, S.STONAME, S.STAMOUNT
    FROM PRODUCT P
    JOIN FACTORY F ON P.FACTNO = F.FACTNO
    JOIN STORE S ON P.PDNO = S.PDNO
    WHERE F.FACLOC = 'SEOUL' AND (S.STAMOUNT IS NULL OR S.STAMOUNT = 0);
END