-- 1. ECOMMERCE 스키마를 생성하시오. 
USE ECOMMERCE;
CREATE SCHEMA ECOMMERCE;

-- 2. 비밀번호가 123QWE!@#인 SHOP_WEB 사용자를 생성하시오
CREATE USER 'SHOP_WEB'@'localhost' IDENTIFIED BY '123QWE!@#';  

-- 3. 비밀번호가 123QWE!@#인 SHOP_ADMIN 사용자를 생성하시오 
CREATE USER 'SHOP_ADMIN'@'localhost' IDENTIFIED BY '123QWE!@#';

 -- 4. SHOP_WEB 사용자에게 ECOMMERCE 스키마에 존재하는 모든 테이블에 대한 SELECT, 
-- INSERT, UPDATE, DELTE 권한을 부여하고 SHOW GRANTS 명령어를 사용해 확인 하시오 
GRANT SELECT, INSERT, UPDATE, DELETE 
ON ECOMMERCE.* TO 'SHOP_WEB'@'localhost';
FLUSH PRIVILEGES;  
SHOW GRANTS FOR 'SHOP_WEB'@'localhost';

-- 5. SHOP_ADMIN 사용자에게 ECOMMERCE 스키마에 대한 모든 권한과, 해당 권한을 다른 
-- 사용자에게 부여할 수 있는 권한을 부여하시오. 이후 SHOW GRANTS 명령어를 사용해 
-- 확인 하시오 

GRANT ALL PRIVILEGES ON ECOMMERCE.* TO 'SHOP_ADMIN'@'localhost' 
WITH GRANT OPTION;
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'SHOP_ADMIN'@'localhost';  

-- 6. SHOP_WEB 의 INSERT 권한을 회수하고 SHOW GRANTS 명령어로 확인 하시오
REVOKE INSERT ON ECOMMERCE.* FROM 'SHOP_WEB'@'localhost';
FLUSH PRIVILEGES;  
SHOW GRANTS FOR 'SHOP_WEB'@'localhost';

-- 7. 'ROLE_WEB' 이란 이름을 가지는 ROLE 을 생성 하시오 
CREATE ROLE ROLE_WEB;

-- 8. 'ROLE_WEB' 에 ECOMMERCE 스키마에 대한 SELECT, INSERT, UPDATE, DELETE, 
-- CREATE 권한을 부여하고 SHOW GRANTS 명령어를 사용해 확인 하시오.
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE ON ECOMMERCE.* TO ROLE_WEB;
SHOW GRANTS FOR ROLE_WEB; 

-- 9. 'ROLE_WEB' ROLE 을 SHOP_WEB 사용자에게 부여 하시오. 
GRANT 'ROLE_WEB' TO 'SHOP_WEB'@'localhost';

-- 10. 'ROLE_WEB'을 SHOP_WEB 사용자로부터 회수 하시오. 
REVOKE 'ROLE_WEB' FROM 'SHOP_WEB'@'localhost';

-- 11.  주어진 ERD 내용대로 USER, ORDER, CATEGORY 테이블을 생성 하시오. 
-- ORDER 와 CATEGORY 테이블의 기본키는 1부터 시작하며 자동으로 1씩 증가하도록 

CREATE TABLE USER(
	Userid VARCHAR(255) PRIMARY KEY,
	Username VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Address TEXT,   
	PhoneNumber VARCHAR(20),   
	regDate TIMESTAMP
);

CREATE TABLE ORDERS(
	OrderID INT PRIMARY KEY AUTO_INCREMENT,
	UserID INT,  
	OrderDate TIMESTAMP NOT NULL,
	TotalAmount DECIMAL(10,2) NOT NULL, 
	ShippingAddress TEXT,  
	IsShipped BOOLEAN
);

CREATE TABLE CATEGORY(
	CategoryID INT PRIMARY KEY AUTO_INCREMENT,
	UpperCategory TEXT,
	CategoryName VARCHAR(255) NOT NULL,
	Description TEXT);
    
-- 12. 주어진 ERD 내용대로 USERFAVORITE 테이블을 생성 하시오. 이때 USERID컬럼이 
-- USER 테이블의 USERID 컬럼을 외래키로 참조하도록 하시오. 기본키는 1부터 시작하며 
-- 자동으로 1씩 증가하도록 지정 하시오. 

CREATE TABLE USERFAVORITE(
	FavoriteID INT PRIMARY KEY AUTO_INCREMENT,
    UserID VARCHAR(255), 
	FOREIGN KEY(UserID) REFERENCES USER(Userid),
	ProductID INT, 
	regDate TIMESTAMP 
);
    
-- 13. 주어진 ERD 내용대로 ORDERDETAIL 테이블을 생성 하시오. 이때 ORDERID컬럼이 
-- ORDER 테이블의 ORDERID 컬럼을 외래키로 참조하도록 하시오. 기본키는 1부터 
-- 시작하며 자동으로 1씩 증가하도록 지정 하시오.

CREATE TABLE ORDERDETAIL(
	OrderDetailID INT PRIMARY KEY AUTO_INCREMENT, 
	OrderID INT,   
	ProductID INT, 
	Quantity INT NOT NULL,
    FOREIGN KEY(OrderID) REFERENCES ORDERS(OrderId)
);

-- 14. 주어진 ERD 내용대로 PAYMENT 테이블을 생성 하시오. 이때 ORDERID컬럼이 
-- ORDER 테이블의 ORDERID 컬럼을 외래키로 참조하도록 하시오. 기본키는 1부터 
-- 시작하며 자동으로 1씩 증가하도록 지정 하시오.

CREATE TABLE PAYMENT(
	PaymentID INT PRIMARY KEY AUTO_INCREMENT,
	OrderID INT,
	PaymentMethod VARCHAR(50) NOT NULL,
	TransactionDate DATE NOT NULL,
	PayAmount DECIMAL(10,2) NOT NULL, 
	IsSuccessful BOOLEAN,
    FOREIGN KEY(OrderID) REFERENCES ORDERS(OrderId)
);

-- 15. 주어진 ERD 내용대로 PRODUCT 테이블을 생성 하시오. 이때 CATEGORYID컬럼이 
-- CATEGORY 테이블의 CATEGORYID 컬럼을 외래키로 참조하도록 하시오.

CREATE TABLE PRODUCT(
	ProductID INT PRIMARY KEY,
	CategoryID INT NOT NULL,
	ProductName VARCHAR(255) NOT NULL, 
	Price DECIMAL(10,2) NOT NULL,
	StockQuantity INT NOT NULL,
	Description TEXT, 
	Manufacturer VARCHAR(100),
	regDate TIMESTAMP,
    FOREIGN KEY(CategoryID) REFERENCES CATEGORY(CategoryID)
);


-- 16. ALTER 구문을 사용하여 USER 테이블의 EMAIL 컬럼에 UNIQUE 제약조건을 지정 

ALTER TABLE USER
ADD CONSTRAINT UNIQUE (EMAIL);
    
-- 17. USER 테이블의 USERNAME 컬럼에 NOT NULL 제약조건 추가 하시오. 

ALTER TABLE USER
MODIFY COLUMN USERNAME VARCHAR(255) NOT NULL;

-- 18. 18. ALTER 구문을 사용하여 PRODUCT 테이블의 STOCKQUANTITY 컬럼의 DEFAULT 
-- 값을 0으로 지정 하시오.

ALTER TABLE PRODUCT
MODIFY COLUMN STOCKQUANTITY INT DEFAULT 0;

-- 19. ALTER 구문을 사용하여 PRODUCT 테이블의 STOCKQUANTITY 컬럼에 0 미만의 값이 
-- 들어갈 수 없도록 CHECK 제약조건을 지정 하시오

ALTER TABLE PRODUCT
ADD CONSTRAINT CHECK (STOCKQUANTITY >= 0);

-- 20. PRODUCT 테이블의 PRODUCTNAME 컬럼에 NOT NULL 제약 조건 추가 하시오.

ALTER TABLE PRODUCT
MODIFY COLUMN PRODUCTNAME VARCHAR(255) NOT NULL;

-- 21. PAYMENT 테이블에 TRANSACTIONDATE 컬럼을 TIMESTAMP 타입으로 변경 하시오. 

ALTER TABLE PAYMENT
MODIFY COLUMN TRANSACTIONDATE TIMESTAMP;

-- 22. CATEGORY 테이블에 UPPERCATEGORY 컬럼을 INT 타입으로 변경 하시오. 

ALTER TABLE CATEGORY
MODIFY COLUMN UPPERCATEGORY INT;

-- 23. CATEGORY 테이블에 DESCRIPTION 컬럼에 NOT NULL 제약조건을 추가 하시오.  

ALTER TABLE CATEGORY
MODIFY COLUMN DESCRIPTION VARCHAR(255) NOT NULL;

-- 24. USERFAVORITE 테이블에 지정되어 있는 외래키 제약조건을 삭제 하시오. 

ALTER TABLE USERFAVORITE
DROP FOREIGN KEY userfavorite_ibfk_1;

SELECT CONSTRAINT_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'USERFAVORITE'
AND COLUMN_NAME = 'UserID';

-- 25. USERFAVORITE 테이블의 USERID 컬럼이 USER 테이블의 USERID 컬럼을 외래키로 
-- 참조하도록 새로운 외래키제약조건을 추가 하시오. 외래키제약조건의 이름은 
-- 'FK_USER_USERFAVORITE' 이며 USER 테이블의 튜플이 생략될 경우 해당 튜플을 
-- 참조하고 있는 USERFAVORITE 테이블 튜플의 USERID컬럼 값은 NULL이 들어가도록 
-- 지정 하시오.
USE ECOMMERCE;

ALTER TABLE userfavorite
ADD CONSTRAINT FOREIGN KEY(USERID) 
REFERENCES USER(USERID)
ON DELETE SET NULL;

-- 26. PAYMENT 테이블에 지정되어 있는 외래키제약조건을 삭제 하시오. 

ALTER TABLE PAYMENT
DROP FOREIGN KEY payment_ibfk_1;

/* 27. PAYMENT 테이블의 ORDERID 컬럼이 ORDER 테이블의 ORDERID컬럼을 외래키로 
참조하도록 새로운 외래키제약조건을 추가 하시오. 외래키제약조건의 이름은 
'FK_ORDER_PAYMENT' 이며 ORDER 테이블의 튜플이 생략될 경우 해당 튜플을 참조하고 
있는 PAYMENT 테이블 튜플도 함께 삭제되도록 하시오. */

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_ORDER_PAYMENT 
FOREIGN KEY(ORDERID) 
REFERENCES ORDERS(ORDERID)
ON DELETE CASCADE;

-- 28. ORDERDETAIL 테이블에 지정되어 있는 외래키제약조건을 삭제 하시오. 

ALTER TABLE ORDERDETAIL
DROP FOREIGN KEY orderdetail_ibfk_1;

/* . ORDERDETAIL 테이블의 ORDERID 컬럼이 ORDER 테이블의 ORDERID 컬럼을 
외래키로 참조하도록 새로운 외래키제약조건을 추가 하시오. 외래키제약조건의 이름은 
'FK_ORDER_ORDERDETAIL' 이며 ORDER 테이블의 튜플이 수정될 경우 해당 튜플을 
참조하고 있는 PAYMENT 테이블 튜플의 ORDERID컬럼의 값에 NULL이 들어가도록 지정 
하시오. */

ALTER TABLE ORDERDETAIL
ADD CONSTRAINT FK_ORDER_ORDERDETAIL
FOREIGN KEY(ORDERID) 
REFERENCES ORDERS(ORDERID)
ON DELETE SET NULL;

/*  30. PRODUCT 테이블에서 기존의 외래키제약조건을 삭제하고 CATEGORYID컬럼이 
CATEGORY 테이블의 CATEGORYID 컬럼을 외래키로 참조하도록 새로운 
외래키제약조건을 추가 하시오. 외래키제약조건의 이름은 'FK_CATEGORY_PRODUCT' 
이며 CATEGORY 테이블의 튜플이 수정될 경우 해당 튜플을 참조하고 있는 PRODUCT 
테이블 튜플의 CATEGORYID컬럼의 값이 함께 수정되도록 지정 하시오*/

ALTER TABLE PRODUCT 
DROP FOREIGN KEY product_ibfk_1;

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_CATEGORY_PRODUCT 
FOREIGN KEY (CATEGORYID) 
REFERENCES CATEGORY(CATEGORYID)
ON UPDATE CASCADE;

-- 31. USER 테이블의 PHONENUMBER 컬럼의 크기를 VARCHAR(15)로 수정 하시오. 

ALTER TABLE USER
MODIFY COLUMN PHONENUMBER VARCHAR(15);

-- 32. USER 테이블에 BIRTHDATE 컬럼을 추가 하시오. 

ALTER TABLE USER
ADD COLUMN BIRTHDATE DATE;

-- 33. PRODUCT 테이블에 WEIGHT 컬럼을 추가 하시오. 

ALTER TABLE PRODUCT
ADD COLUMN WEIGHT INT;

-- 34. 34. USER 테이블에 BIRTHDATE 컬럼을 삭제 하시오.

ALTER TABLE USER
DROP COLUMN BIRTHDATE;

-- 35. PRODUCT 테이블에 WEIGHT 컬럼을 삭제 하시오.

ALTER TABLE PRODUCT
DROP COLUMN WEIGHT;

-- 36. USER 테이블의 USERNAME 과 EMAIL 컬럼의 순서를 변경 하시오. 

ALTER TABLE USER
MODIFY COLUMN EMAIL VARCHAR(255) AFTER USERNAME;

-- 37. USER 테이블의 REGDATE 컬럼의 이름을 CREATEDAT 으로 변경 하시오. 

ALTER TABLE USER
CHANGE COLUMN REGDATE CREATEDAT TIMESTAMP;

-- 38. ORDERDETAIL 테이블의 PRIMARY KEY 를 (ORDERID, PRODUCTID)의 복합키로 
-- 변경 하시오. 

ALTER TABLE ORDERDETAIL 
ADD CONSTRAINT UNIQUE (ORDERID, PRODUCTID);

/*
9. PAYMENT 테이블의 TRASACTIONDATE 컬럼의 DEFAULT 값을 행이 삽입될때 날짜와 
시간으로 지정하고, 만약 해당 튜플이 수정 될 경우 수정시간으로 자동으로 변경되도록 
하시오. 
*/

ALTER TABLE PAYMENT 
MODIFY COLUMN TRANSACTIONDATE 
TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
ON UPDATE CURRENT_TIMESTAMP;


-- 40 . PRODUCT, ORDERDETAIL, USERFAVORITE, PAYMENT , USER, ORDER, CATEGORY 
-- 테이블을 삭제 하시오.

DROP TABLE  PRODUCT, ORDERDETAIL, USERFAVORITE, PAYMENT , USER, ORDERS, CATEGORY;
