CREATE DEFINER=`root`@`localhost` PROCEDURE `GetEmp_ReS`()
BEGIN
-- Q14) CTE 사용해서 MGR 상관부터 말단까지 구조를 탐색해보자.
-- [1] 최상의 정보 출력해보장.

WITH RECURSIVE EMP_RES AS (

	SELECT EMPNO, ENAME, MGR, 1 AS LEVEL
    FROM EMP
    WHERE MGR IS NULL
   UNION ALL
	
	 SELECT E.EMPNO, E.ENAME, E.MGR , ET.LEVEL+1
	 FROM EMP E
	JOIN EMP_RES ET ON E.MGR = ET.EMPNO

)

SELECT EMPNO, ENAME, MGR, LEVEL
FROM EMP_RES
ORDER BY LEVEL, MGR, EMPNO;
END