CREATE DEFINER=`root`@`localhost` PROCEDURE `02_GuGuDan`()
BEGIN
WITH RECURSIVE GUGUDAN AS(
	SELECT 3 AS DAN, 1 AS NUM, 3*1 AS RESULT
    
    UNION ALL
    
    SELECT DAN, NUM+1, DAN * (NUM+1)
    FROM  GUGUDAN
    WHERE NUM<9
    )
    SELECT CONCAT(DAN, " * ", NUM , " = ", RESULT ) AS GUGUDAN_PRN
    FROM GUGUDAN;
END