-- 3. 신규 테이블을 만들어 폐기되는 모든 데이터를 관리하고자 한다.
use workshop;

CREATE TABLE DISCARDED_PRODUCT (
	PDNO INT,
    PDNAME VARCHAR(10),
    PDSUBNAME VARCHAR(10),
    FACTNO VARCHAR(5),
    PDDATE DATE,
    PDCOST INT,
    PDPRICE INT,
    PDAMOUNT INT,
    DISCARDED_DATE DATE,
    PRIMARY KEY(PDNO),
    FOREIGN KEY (FACTNO) REFERENCES FACTORY (FACTNO)
);